[program:video-portal-update]
command=python3 /home/pi/video-portal/current/updater/updater.py
directory=/home/pi/video-portal/current
user=pi
environment=HOME="/home/pi",USER="pi",LOGNAME="pi"
autostart=false
autorestart=false
startsecs=0
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/home/pi/video-portal/updates/logs/supervisor-video-portal-update.log
